### ISSUE TITLE
Bizarre SQL error we can't figure out

### ISSUE THREAD

**Issue by GavJenks** [DevotedMC/BanStick#13]
We had 6 exclusions in bs_exclusion, and types a command "/untangle [4 names]"
It said in game in green "it worked!" text that it added 4 exclusions and deleted 6 exclusions.

But in the logs, it says

> [09:15:37] [Server thread/ERROR]: [BanStick] Removal of Exclusion failed: 171
> com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for th
> e right syntax to use near '* FROM bs_exclusion WHERE eid = 171' at line 1

the only part of the code mentioning "removal of exclusion failed" though is BSExclusion class, which only mentioned a DELETE statement, not a SELECT, and no "*", so ... wat?

and why would it have a problem here anyway? And why would it report that it worked when it didn't?

**Comment by ProgrammerDan** [comment]
These are excellent questions. I wonder if @Maxopoly has any insight?

**Comment by GavJenks** [comment]
Followup: We have determined that it only affects DB, the hashmap goes through and it works until next restart

**Comment by Maxopoly** [comment]
Fixed almost a year ago https://github.com/DevotedMC/BanStick/commit/a8fb6707c976dd64c57bc28e2863eafd9e26f38b

**Comment by ProgrammerDan** [comment]
Just need a new build then, eh?

**Comment by Maxopoly** [comment]
I would assume so

**Comment by GavJenks** [comment]
yup that worked, sorry!
