### ISSUE TITLE
java.sql.SQLException: Can't create table `central`.`bs_player` (errno: 150 "Foreign key constraint is incorrectly formed")

### ISSUE THREAD

**Issue by RainOfPain125** [DevotedMC/BanStick#16]
https://www.toptal.com/developers/hastebin/fipikiroca.sql

The "Bastion" plugin was misbehaving. According to other issues, the developer did not care to make it compatible with MySQL or something. They suggested the player change to MariaDB. I went through the pain of changing everything over to MariaDB, and now this plugin is throwing a fit.

The database is clean, brand new. just installed this crap.

**Comment by ProgrammerDan** [comment]
iirc I have the table create order backwards or something. I stopped maintaining this, but the CivClassic fork might have fixes.

**Comment by ProgrammerDan** [comment]
if you are recompiling from source, do the following:

1) remove this line: https://github.com/DevotedMC/BanStick/blob/master/src/main/java/com/programmerdan/minecraft/banstick/handler/BanStickDatabaseHandler.java#L232

2) Then, either add as a new migration, or run in your DBMS after installation:
`ALTER TABLE bs_player ADD FOREIGN KEY (bid) REFERENCES bs_ban(bid);`

**Comment by RainOfPain125** [comment]
ah, I see. I am using the CivClassic version from here ( https://github.com/CivClassic/AnsibleSetup/tree/master/jarfiles/public/plugins )

I'm sorry for bothering you. I don't know how to "recompile" anything, so I'll just move my issue to there.

**Comment by ProgrammerDan** [comment]
Not a bother -- good luck in your quest!
